export const Endpoints = {
  LOGIN: "/token/",
  TOKEN_REFRESH: "/token/refresh/",
  REGISTER: "/register/",
  LOGOUT: "/logout/",
  FIREBASE_AUTH: "/auth/firebase/",
  FORGOT_PASSWORD: "/forgot-password/",
  VERIFY_OTP: "/verify-otp/",
  RESET_PASSWORD: "/reset-password/",
  CHANGE_PASSWORD: "/change-password/",

  ME: "/me/",
  PROFILE_STOCK_ALERTS: "/users/profile/stock-alerts/",
  DEVICES: "/devices/",
  DEVICE_DETAIL: (token: string) => `/devices/${encodeURIComponent(token)}/`,

  ADDRESSES: "/addresses/",
  ADDRESS_DETAIL: (id: number) => `/addresses/${id}/`,
  ADDRESS_SET_DEFAULT: (id: number) => `/addresses/${id}/set-default/`,

  PRODUCTS: "/products/",
  PRODUCTS_LOW_STOCK: "/products/low-stock/",
  PRODUCTS_BEST_SELLING: "/products/best-selling/",
  PRODUCT_DETAIL: (id: number) => `/products/${id}/`,
  BANNERS: "/banners/",
  CATEGORIES: "/categories/",
  CATEGORIES_TREE: "/categories/tree/",
  CATEGORY_DETAIL: (id: number) => `/categories/${id}/`,
  SEARCH: "/search/",

  CART_ME: "/carts/me/",
  CART: "/cart-items/",
  CART_ADD: "/cart-items/",
  CART_UPDATE: (id: number) => `/cart-items/${id}/`,
  CART_REMOVE: (id: number) => `/cart-items/${id}/`,

  ORDERS: "/orders/",
  MY_ORDERS: "/my-orders/",
  ORDER_DETAIL: (id: string) => `/orders/${id}/`,
  MY_ORDER_DETAIL: (id: string) => `/my-orders/${id}/`,
  ORDER_CREATE: "/orders/",
  ORDER_CANCEL: (id: string) => `/my-orders/${id}/cancel/`,
  ORDER_UPDATE_STATUS: (id: string) => `/orders/${id}/update-status/`,
  ORDER_CALCULATE_SHIPPING: "/orders/calculate-shipping/",
  ORDER_PAY_VNPAY: (id: string | number) => `/my-orders/${id}/pay-vnpay/`,
  ORDER_VERIFY_VNPAY: (id: string | number) => `/my-orders/${id}/verify-vnpay/`,
  REVENUE_SUMMARY: "/reports/revenue/summary/",
  REVENUE_RANGE: "/reports/revenue/range/",
  VOUCHERS: "/vouchers/",
  MY_VOUCHERS: "/my-vouchers/",
  VOUCHER_CLAIM: (voucherId: number | string) =>
    `/vouchers/${voucherId}/claim/`,
  VOUCHER_APPLY: "/vouchers/apply/",
  SUPPORT_SEND: "/support/send/",

  REVIEWS: (_pid: number) => "/reviews/",
  REVIEW_DETAIL: (id: number | string) => `/reviews/${id}/`,
  REVIEW_REPLY: (id: number | string) => `/reviews/${id}/reply/`,
  REVIEW_MEDIA: (id: number | string) => `/reviews/${id}/media/`,
  REVIEW_MEDIA_DETAIL: (id: number | string, mediaId: number | string) =>
    `/reviews/${id}/media/${mediaId}/`,
} as const;
