# Generated by Django 6.0.2 on 2026-04-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
