# Generated by Django 6.0.2 on 2026-04-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_address_lat_alter_address_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_stock_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
