# Generated by Django 6.0.2 on 2026-04-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_reviewmedia_delete_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('BHX', 'Bách Hóa Xanh'), ('WINMART', 'WinMart')], default='BHX', max_length=20)),
                ('external_id', models.CharField(help_text='ID của sp trên web đối thủ', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm đối thủ',
                'verbose_name_plural': 'Sản phẩm đối thủ',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
