# Generated by Django 6.0.2 on 2026-04-14 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_crawlerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerproduct',
            name='target_category',
            field=models.ForeignKey(blank=True, help_text='Chọn trước danh mục của Shop để bỏ hàng vào (Sẽ ưu tiên dùng danh mục này khi Duyệt)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
    ]
