# Generated by Django 6.0.2 on 2026-04-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_voucher_uservoucherusage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uservoucherusage',
            new_name='store_userv_user_id_7c4140_idx',
            old_name='store_userv_user_vo_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='store_vouch_code_b98f0e_idx',
            old_name='store_vouch_code_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='store_vouch_end_dat_415f31_idx',
            old_name='store_vouch_end_dat_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='store_vouch_is_acti_d64d95_idx',
            old_name='store_vouch_is_acti_idx',
        ),
    ]
