# Generated by Django 6.0.2 on 2026-04-17 02:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_uservoucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm xác nhận hoàn thành đơn hàng (dùng cho báo cáo doanh thu).', null=True),
        ),
        migrations.AlterField(
            model_name='crawlerproduct',
            name='target_category',
            field=models.ForeignKey(blank=True, help_text='Danh mục shop sẽ gán khi duyệt sản phẩm này', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='total = subtotal + shipping_fee - discount_amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='uservoucherusage',
            name='order',
            field=models.OneToOneField(help_text='1 đơn hàng chỉ được áp dụng 1 voucher.', on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usage', to='store.order'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(db_index=True, help_text='Mã giảm giá. Tự động normalize UPPERCASE khi lưu.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Giảm theo phần trăm'), ('FIXED', 'Giảm số tiền cố định')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='PERCENT: 0-100. FIXED: số tiền VNĐ.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[Chỉ dùng với PERCENT] Mức giảm tối đa (VNĐ). NULL = không giới hạn.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_usage',
            field=models.PositiveIntegerField(blank=True, help_text='Tổng lượt dùng tối đa. NULL = không giới hạn.', null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_usage_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Số lượt tối đa mỗi user. Mặc định: 1.'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá trị đơn tối thiểu để áp dụng mã.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
