# Generated by Django 6.0.2 on 2026-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_options_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_log',
            field=models.JSONField(blank=True, help_text='Raw JSON từ IPN MoMo — dùng giải quyết khiếu nại.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('MOMO', 'Ví điện tử MoMo')], default='COD', help_text='Phương thức thanh toán khách chọn lúc đặt hàng.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='UNPAID', help_text='Trạng thái thanh toán: UNPAID → PAID / FAILED / REFUNDED.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Mã giao dịch MoMo (transId) — dùng đối soát tài chính.', max_length=100, null=True),
        ),
    ]
