# Generated by Django 6.0.2 on 2026-04-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_add_payment_fields_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_log',
            field=models.JSONField(blank=True, help_text='Raw JSON từ IPN — dùng giải quyết khiếu nại.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('VNPAY', 'Cổng thanh toán VNPAY')], default='COD', help_text='Phương thức thanh toán khách chọn lúc đặt hàng.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Mã giao dịch cổng thanh toán (transId/vnp_TransactionNo) — dùng đối soát tài chính.', max_length=100, null=True),
        ),
    ]
