# Generated by Django 6.0.2 on 2026-04-24 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_order_payment_log_alter_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Địa chỉ', 'verbose_name_plural': 'Địa chỉ'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner quảng cáo', 'verbose_name_plural': 'Banner quảng cáo'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Sản phẩm trong giỏ', 'verbose_name_plural': 'Sản phẩm trong giỏ'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sản phẩm trong đơn', 'verbose_name_plural': 'Sản phẩm trong đơn'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='reviewmedia',
            options={'verbose_name': 'Ảnh/Video đánh giá', 'verbose_name_plural': 'Ảnh/Video đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='storelocation',
            options={'verbose_name': 'Vị trí cửa hàng', 'verbose_name_plural': 'Vị trí cửa hàng'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Tin nhắn hỗ trợ', 'verbose_name_plural': 'Tin nhắn hỗ trợ'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'Yêu cầu hỗ trợ', 'verbose_name_plural': 'Yêu cầu hỗ trợ'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPING', 'Đang giao hàng'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web Browser')], default='android', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thiết bị FCM',
                'verbose_name_plural': 'Thiết bị FCM',
                'indexes': [models.Index(fields=['user', 'is_active'], name='store_fcmde_user_id_39b01e_idx')],
            },
        ),
    ]
